### ISSUE TITLE
Support missing keywords

### ISSUE THREAD

**Issue by dirk-thomas** [lucas-clemente/language-cmake#14]
The following keywords (https://cmake.org/cmake/help/v3.5/command/if.html) are currently not highlighted atm. These are just examples, there might be others missing:
* `MATCHES`
* `STR*`
* `VERSION_*`
* `IN_LIST`

The comment in the code (https://github.com/lucas-clemente/language-cmake/blob/e592aafeb0798a6af24b72bff3d7dc388c86157a/grammars/cmake%20listfile.cson#L59) suggests that the list can be updated somehow automatically. From the text alone I couldn't figure out how this should be done. Is there any more information about that process? Then I would be happy to provide a PR for this.

**Comment by lucas-clemente** [comment]
Thanks for the report! I think you can just add them to the regex, I'd be happy to accept a PR :)
