### ISSUE TITLE
Support for CMake 3.0+ Multiline Comments

### ISSUE THREAD

**Issue by bhgomes** [lucas-clemente/language-cmake#19]
It is written with a starting `#[[` and a closing `]]`.
Example from the docs:

    #[[THIS IS A BRACKET COMMENT.
    IT RUNS UNTIL THE CLOSE BRACKET.]]
    message("First Argument\n" #[[BRACKET COMMENT]] "Second Argument")

(the words in uppercase are the "multiline comments". Case change is added in for effect and does not appear in the original documentation)

Here is a link to the docs: [_bracket-comment_](https://cmake.org/cmake/help/v3.1/manual/cmake-language.7.html#bracket-comment)

**Comment by lucas-clemente** [comment]
I don't have the time to update this package, but I'm happy to review / merge a PR.

**Comment by PhydeauxLeChien** [comment]
This was already added in #18, just needs a release.

**Comment by lucas-clemente** [comment]
Pushed a release.
