### ISSUE TITLE
Add highlight support for CMake modules

### ISSUE THREAD

**Issue by gang65** [lucas-clemente/language-cmake#22]
Currently modules are not supported by Highlight tools.
The most commonly used module: ExternalData, feature_summary, ExternalProject and FetchContent are not supported:
https://cmake.org/cmake/help/v3.12/module/ExternalProject.html
https://cmake.org/cmake/help/git-stage/module/FetchContent.html
https://cmake.org/cmake/help/git-stage/module/FeatureSummary.html
https://cmake.org/cmake/help/v3.12/module/ExternalData.html

Some real life examples of usage could be found at:
https://mirkokiefer.com/cmake-by-example-f95eb47d45b1

Full list of all available modules are available at:
https://cmake.org/cmake/help/v3.14/manual/cmake-modules.7.html

It will be great to add highlight support for these commands. Thanks

**Comment by TrinityCoder** [comment]
Hello,

I have created the pull request #24 which resolves this request. Ideally, it would be best if we could just use the [arg_separators.rb](https://gist.github.com/TrinityCoder/c1c011f12c54c8ee8a1121bc9c2a21cd) script to extract the argument constants, but when I replaced `--help-command-list` by `--help-module-list` and `--help-command` by `--help-module`, the script does not print anything. So I went to the docs of each module and updated the `cmake listfile.cson` file manually. Automated solution would be definitely better!
