### ISSUE TITLE
The ON and TRUE keywords are not colourized

### ISSUE THREAD

**Issue by ldionne** [lucas-clemente/language-cmake#7]
Actually, seeing how GitHub does not colourize them either, I think this issue is more a question. Why are these keywords not colourized (both in your theme and by GitHub)?

```cmake
TRUE
FALSE

ON
OFF
```

**Comment by lucas-clemente** [comment]
No idea, my guess would be someone forgot it and all grammar files got derived from the same base?

Anyway, I've pushed a fix and published it as 0.1.4.

**Comment by ldionne** [comment]
That's funny. Thanks a lot for the fix!
