### ISSUE TITLE
highlight for .in files

### ISSUE THREAD

**Issue by dirk-thomas** [lucas-clemente/language-cmake#9]
CMake uses `.in` files as templates in the function `configure_file`. It would be great if these files would also be highlighted. Due to the nature of being a template this package can only highlight very few parts, e.g. `@VAR_NAME@`.

In a similar package which provides syntax highlighting to EmPy templates (https://atom.io/packages/language-empy) I use a second file extension to describe the language of the expanded file, e.g. `filename.xml.em`. `language-empy` highlights only the template logic and then refers to an existing language to highlight the rest, in this case xml. While it is kind of annoying having to list the various second level extensions that was the only way I could come up with.

Would this feature be reasonable for this package or would you like to keep it in a separate package like `language-cmake-in`? I am happy to contribute if you think it makes sense to be added to `language-cmake`.

**Comment by lucas-clemente** [comment]
Thanks for the report! I wasn't aware of `.in` files before. Your solution of adding a separate language  sounds fine to me, I would be happy to merge a PR!

I'm on vacation right now, so I might take some time replying / reviewing :)

**Comment by dirk-thomas** [comment]
It would actually be multiple grammar files. First of all one for `.in`. And then based in that whatever language you want to imagine - I would probably add the following for now:
* `.cmake.in`
* `.py.in`
* `.sh.in`

**Comment by lucas-clemente** [comment]
I see. As long as the list stays short and it's not too much duplicate stuff I'm fine with that :)

**Comment by dirk-thomas** [comment]
For now I just added the sub languages I use in combination with `.in` files (Batch, C, CMake, C++, Python, Shell Script). There should be no duplication since the sub-language grammars only reference the other grammars. Please see #10.

**Comment by lucas-clemente** [comment]
I've merged and published #10 in 0.2.0. Thanks again for your help! :)

**Comment by dirk-thomas** [comment]
Thanks for the fast replies.

**Comment by felixsanz** [comment]
@lucas-clemente @dirk-thomas In this PR, the `cmake template cmake.cson` file is confusing. It also contains `'include': 'source.cmake'` which i can't find anywhere. Where is that grammar?

Thanks

**Comment by dirk-thomas** [comment]
Are you looking for this one? https://github.com/lucas-clemente/language-cmake/blob/e592aafeb0798a6af24b72bff3d7dc388c86157a/grammars/cmake%20listfile.cson#L148

**Comment by felixsanz** [comment]
Yeah...

Damn, i feel stupid now hah. Sorry!

Anyway it feels redundant isn't it? "CMake template CMake". Shouldn't this just be "CMake template"? I'm trying to understand what's this file for but i can't find anything.

**Comment by dirk-thomas** [comment]
The first part "CMake template" describes that it is a CMake `.in` file which is being expanded using `configure_file`.

The second part describes the language of the expanded template - in this case also CMake. But there are several other grammars where the expanded file is a different language, e.g. Python https://github.com/lucas-clemente/language-cmake/blob/master/grammars/cmake%20template%20python.cson

**Comment by felixsanz** [comment]
Thank you!
